// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vskkyalcisotyfokkuxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZza2t5YWxjaXNvdHlmb2trdXhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMDc3NjksImV4cCI6MjA2ODY4Mzc2OX0.1qK7ikRiJSs9THCqfIejQlodhJ6mWE3Ys8PSfwHJPKk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});